version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 54321:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: nest 
    networks:
      - freenetwork
networks:
  freenetwork: